//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwo.LiveRegistration.Plugins.Models
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum appaction_ClientType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Browser = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mobile = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailApp = 2,
	}
}