//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwo.LiveRegistration.Plugins.Models
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_oc_daysofweek
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sun = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mon = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tue = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wed = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Thu = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fri = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sat = 192350006,
	}
}