//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwo.LiveRegistration.Plugins.Models
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum mwo_ImageType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Both = 122870002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 122870010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostImage = 122870001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreImage = 122870000,
	}
}