//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwo.LiveRegistration.Plugins.Models
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum mwo_EventHandlerType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PluginType = 122870000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceEndpoint = 122870001,
	}
}