//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwo.LiveRegistration.Plugins.Models
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_SupportedDeployment
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Both = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDynamics365ClientforOutlookOnly = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServerOnly = 0,
	}
}