//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwo.LiveRegistration.Plugins.Models
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ServiceEndpoint_NamespaceFormat
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NamespaceAddress = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NamespaceName = 1,
	}
}