//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwo.LiveRegistration.Plugins.Models
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ServiceEndpoint_MessageFormat
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BinaryXML = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Json = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TextXML = 3,
	}
}